version: '3'

services:
###> doctrine/doctrine-bundle ###
  tododb:
     image: 'mysql:latest'
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: main
     ports:
        - '3306:3306'
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: todoPma
    links:
      - tododb
    environment:
      PMA_HOST: tododb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8084:80
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
